### ISSUE TITLE
Cannot convert local mp3 file to text

### ISSUE THREAD

**Issue by uemirhanselim** [azkadev/whisper_dart#1]
First of all, I appreciate you made this package. I integrated whisper package to my flutter app but when I give my local mp3 file to audioInput it says 'audio input not found'.

`void main(List<String> arguments) {
  DateTime time = DateTime.now();
  // print(res);
  Whisper whisper = Whisper(
    whisperLib: "whisper.cpp/whisper.so",
  );
  try {
    var res = whisper.request(
      whisperRequest: WhisperRequest.fromWavFile(
        audio: WhisperAudioconvert.convert(
          audioInput: File(
              "/home/hexaminate/Documents/HEXAMINATE/app/ai/whisper_dart/samples/audio.ogg"),
          audioOutput: File(
              "/home/hexaminate/Documents/HEXAMINATE/app/ai/whisper_dart/samples/output.wav"),
        ),
        model: File(
            "/home/hexaminate/Documents/HEXAMINATE/app/ai/whisper_dart/models/ggml-model-whisper-small.bin"),
      ),
    );
    print(res.toString());
    print(convertToAgo(time.millisecondsSinceEpoch));
  } catch (e) {
    print(e);
  }
}`

the message console's give me is;

-flutter: audio input not found

**Comment by azkadev** [comment]
Change the audio path, and make sure you have compiled the library, downloaded the model, and prepared wav audio
