### ISSUE TITLE
Has anyone tried the flutter example on iOS?

### ISSUE THREAD

**Issue by bljubisic** [azkadev/whisper_dart#2]
I have tried to run example of the whisper model using flutter but even when build the whisper.cpp library and embedding it in the Xcode project it failed with:
flutter: Invalid argument(s): Failed to lookup symbol 'request': dlsym(RTLD_DEFAULT, request): symbol not found

I have located this error in whisper_dart.dart on line 38:
 var res = openLib(whisperLib: whisperLib).lookupFunction<whisper_request_native, whisper_request_native>("request").call(whisperRequest.toString().toNativeUtf8());

This lookupFunction returns null, even with the dylib loaded. Is there any way to get pass this?

**Comment by bljubisic** [comment]
I have fixed this by using whisper.cpp project and their cpp code. Integrating this code together with main.cpp from this project makes everything working.

**Comment by srv1n** [comment]
@bljubisic  Any chance you could share a sample iOS app? Thanks!
