### ISSUE TITLE
It's running but it's taking too long to translate. Is this normal?

### ISSUE THREAD

**Issue by williamidt** [azkadev/whisper_dart#6]
Hello friend, you did a good job and I cloned the example you created .. I downloaded the download model and a 20 second audio of mine .. however it is taking too long to transcribe .. approximately 5 minutes do you know if this is normal? I'm trying to use the package in an application I'm creating. Thanks in advance for your help :)

**Comment by azkadev** [comment]
If you use an old version of my library you have to add code isolates, but in my new library you don't need to add manually, if translate is still old it's possible the hardware specs are low

Btw sorry my english is bad

**Comment by williamidt** [comment]
Hi @azkadev, 
I updated to  whisper_dart version 0.0.10 that have isolates. It's running ok but it's continues taking a long time to transcribe to english.

I have this git if you would like to see 
https://github.com/williamidt/whisper_dart_my_first_test_v2

So I intent to test running whisper with module go to flutter .. to see if run more fast, I need this whisper to the finished a app that i'm finalizing

Thanks in advanced,
Tmj

**Comment by williamidt** [comment]
Hi @JeisonSanches, how are you?

As you are from Brazil... I also live here in São Paulo... I ended up taking the liberty of contacting you because you have contributed to this package.

I tested the whisper_dart package and it's running.. but it's taking a long time to do the transcription.. 4~5minutes.. for a small audio of 20~30 seconds.. Does this happen to you on android?

Thanks in advance for your help and feedback.. If you want I also have a git that I tested.. the link is in the previous post.

Is there somewhere I can contact you.. I tried your Github but I couldn't find a place..

tmj

**Comment by JeisonSanches** [comment]
@williamidt Com esse tempo reportado, você provavelmente deve ter compilado em modo debug, certo? Compile em modo release que você notará imediatamente um melhora brutal no tempo de processamento. Além disso, outra coisa que você pode fazer para melhorar a performance, é invocar o código nativo usando `Isolate.run`. 

Você pode entrar em contato comigo pelo meu twitter @JeisonSanches (não acho que seja uma boa ideia divulgar meu e-mail por aqui).

**Comment by williamidt** [comment]
@JeisonSanches obrigado pelo retorno. 
.
Realmente eu baixei novamente aqui e testei o exemplo de vcs do próprio package e roda bem mais rápido na versão release e debug tbm.. Mas o jeito que eu estava fazendo acredito que esteja errado pq eu copiei o exemplo do readme e fiz um app de teste mas quando rodava dava erro de nao encontrar a libwhisper.so, dai eu peguei o arquivo .so e coloquei dentro do diretorio do android e configurei o buid.grade.. dai rodou.. 
..
a minha duvida é a seguinte, eu pensei que precisaria apenas importar o package no pubspec whisper_dart ou whisper_flutter, colocar o codigo.. whisper.request.. que faria a transcrição... mas acho que tem compilar a lib antes para android, windows ios etc.. isso?
..
eu to criando de aplicativo de tradução.. ja está tudo rodando porém estou com problema na parte de fala offline.. o whisper me ajudaria a resolver esse problema.. eu programo faz pouco tempo em flutter e tbm nao conheço integração com biblioteca c++ 
.
Mesmo assim agradeço sua ajuda, 

tmj
